### ISSUE TITLE
[Предложение] Добавить в информер кол-во сделанных бросков в тюрьме

### ISSUE THREAD

**Issue by BaHeK1994** [alexdymov/m1pro#4]
Иногда игра долго тянется и забываешь сколько у тебя бросков в тюрьме. Полезно в быстром режиме, когда при выходе до 3-го броска появляется 3-ий кубик.

Коммит: https://github.com/alexdymov/m1pro/commit/cf11170a4dd6a65a2edcce0a4fb8d931ec5bba8e
Не сделал PR, т.к. у меня висит предыдущий коммит с автоматическим стартом соревновательного режима.

**Comment by alexdymov** [comment]
По этому поводу уже были просьбы сделать что-то. Согласен, иногда непонятно сколько еще осталось "сидеть".
Определенно, возможность видеть оставшееся количество бросков стоит реализовать, но реализация в данном коммите учитывает только собственного игрока. Также информация о бросках расположена в блоке предназначенном для информации об игровом столе, что не очень хорошо.
Я считаю, что такую информацию будет полезнее видеть для всех игроков за столом, соответственно, логичнее будет отображать количество оставшихся бросков числом непосредственно в фишке игрока (по аналогии с пропуском хода и ходом назад).

Касательно прошлого PR, в нем я расписал минусы такого подхода и имеющееся альтернативное решение.

**Comment by BaHeK1994** [comment]
`Касательно прошлого PR, в нем я расписал минусы такого подхода и имеющееся альтернативное решение.`

Я понял, просто я использую этот коммит для себя и не знаю как без него сделать PR без удаления коммита, возможно отдельную ветку создать надо будет, позже с этим разберусь.

```Я считаю, что такую информацию будет полезнее видеть для всех игроков за столом, соответственно, логичнее будет отображать количество оставшихся бросков числом непосредственно в фишке игрока (по аналогии с пропуском хода и ходом назад).```
Да, так наверно будет лучше, но я не нашел в массиве данных, сколько бросков необходимо сделать в тюрьме, возможно это константа.
