### ISSUE TITLE
Не подсвечивается поле шанс-телепорт, после автобуса

### ISSUE THREAD

**Issue by BaHeK1994** [alexdymov/m1pro#6]
Плавающая ошибка, иногда не подсвечивается поле шанс-телепорт, после того как игрок выбрал позицию на автобусе.

Игра: https://monopoly-one.com/m1tv/#/40/6QJvQlH2idNTH5wA
Время: 21:00

Событие **currentTeleports** произошло раньше, чем **currentChooses**

Прикрепляю видео и скрин из консоли.
https://user-images.githubusercontent.com/18642618/180458649-301a9db4-255f-40a0-9773-802907705f23.mp4
![изображение](https://user-images.githubusercontent.com/18642618/180458767-01e8875d-f578-4cf4-9d97-bbcd6ae59e82.png)

**Comment by alexdymov** [comment]
fixed in 1.1.0
