### ISSUE TITLE
игра вообще не изменена

### ISSUE THREAD

**Issue by CF-Trail** [alexdymov/m1pro#8]
![image](https://github.com/alexdymov/m1pro/assets/106690765/19360525-dffd-4580-a3e0-f218f04e7eae)
работает только хаб, остальное не тронуто

**Comment by CF-Trail** [comment]
![image](https://github.com/alexdymov/m1pro/assets/106690765/e4a56493-d822-4d01-b1bf-04fd2cf6a783)

**Comment by oakwire7** [comment]
Попробуй почистить cookies
